type: object
required: ["homeserver", "username_prefix"]
properties:
  homeserver:
    type: object
    required: ["server_name", "url"]
    properties:
      server_name:
        type: string
      url:
        type: string
#      media_url:
#        type: string
#      max_upload_size:
#        type: number
      appservice_port:
        type: number
      appservice_host:
        type: string
  tls:
    type: object
    required: ["key_file", "crt_file"]
    properties:
      key_file:
        type: string
      crt_file:
        type: string
  username_prefix:
    type: string

  slack_hook_port: 9898

  logging:
    type: object
    properties:
      console:
        type: "string"
        enum: ["error", "warn", "info", "debug", "off"]
      fileDatePattern:
        type: string
      timestampFormat:
        type: string
      files:
        type: "object"
        items:
          additionalProperties:
            - type: "string"
              enum: ["error","warn","info","debug"]
  bot_profile:
    type: object
    properties:
      displayname:
        type: string
      avatar_url:
        type: string
  encryption:
    type: object
    properties:
      enabled:
        type: boolean
      pantalaimon_url:
        type: string
    required: ["enabled"]
