type: object
required: ["homeserver", "username_prefix"]
properties:
  homeserver:
    type: object
    required: ["server_name", "url"]
    properties:
      server_name:
        type: string
      url:
        type: string
#      media_url:
#        type: string
#      max_upload_size:
#        type: number
      appservice_port:
        type: number
      appservice_host:
        type: string
  username_prefix:
    type: string

  logging:
    type: object
    properties:
      console:
        type: "string"
        enum: ["error", "warn", "info", "debug", "off"]
      fileDatePattern:
        type: string
      timestampFormat:
        type: string
      files:
        type: "object"
        items:
          additionalProperties:
            - type: "string"
              enum: ["error","warn","info","debug"]
