homeserver:
  # The domain name of your homeserver
  #
  server_name: my.server.here

  # The URL for connecting to your homeserver
  #
  url: http://localhost:8008

  # The public facing url for media on your homeserver.
  # This is usually the public url of your homeserver.
  # Optional. Defaults to the value of `url`.
  #
  #media_url: "http://my.server.here"

  # Optional. The maximum size of a uploaded file to Matrix in bytes. No limit by default
  #
  #max_upload_size: 104857600

  # Optional. Used to specify the port of the appservice in the config, rather than the command line.
  # This will be overriden by any ports given in the process arguments.
  #
  #appservice_port: 5858

  # Optional. Used to specify the host to listen on for the appservice.
  # appservice_host: 0.0.0.0

# The prefix to give Slack users on the Matrix server
#
username_prefix: "tierce_"

# Optional. TLS files to be used when handling Slack requests
#tls:
  #key_file: /path/to/tls.key
  #crt_file: /path/to/tls.crt

# Port for incoming Slack requests from webhooks and event API messages
# Optional if using RTM API, required otherwise.
#
slack_hook_port: 9898

# Optional
# logging:
#   console: "info" # One of "debug", "info", "warning", "error", "silent"

#   # Files that the bridge may log into. The key is the minimum level to report.
#   #
#   files:
#       "./debug.log": "info"
#       "./error.log": "error"

# # Optional. Set the bot's profile on startup
bot_profile:
  # Optional. Set the displayname.
  #
  displayname: "Bridge Bot"
